"""Import CMake's resolved Metalium consumer requirements without export sets.

The codemodel is generated by the pinned runtime's own CMake recipes. Only the
two ANN consumer probes are read: unrelated dependencies and imported tools do
not become exported targets. The snapshot belongs to one node/configuration.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import shlex


def literal(value: str) -> str:
    """CMake bracket quoting, including paths/definitions containing quotes."""
    equals = '=='
    while f']{equals}]' in value:
        equals += '='
    return f'[{equals}[{value}]{equals}]'


def arguments(fragments: list[dict]) -> list[str]:
    return [word for entry in fragments for word in shlex.split(entry['fragment'])]


def compile_group(target: dict) -> dict:
    groups = target.get('compileGroups', [])
    if len(groups) != 1 or groups[0]['language'] != 'CXX':
        raise ValueError(f"Expected one C++ consumer group: {target['name']}")
    group = groups[0]
    if group.get('precompileHeaders') or group.get('frameworks'):
        raise ValueError('Prebuilt snapshots do not support consumer PCH or framework headers')
    if group.get('languageStandard', {}).get('standard', '20') != '20':
        raise ValueError('The runtime requires a different C++ standard from the ANN build')
    return group


def property_line(target: str, name: str, values: list[str]) -> str:
    if not values:
        return ''
    # Escape list separators in individual values, without interpreting quotes,
    # dollar signs or backslashes through a generated CMake quoted string.
    values = [value.replace(';', r'\;') for value in values]
    return f'set_property(TARGET {target} PROPERTY {name} {literal(";".join(values))})\n'


def snapshot(build: Path, configuration: str, output_dir: Path | None = None) -> list[str]:
    build = build.resolve()
    output_dir = output_dir.resolve() if output_dir else build
    reply = build / '.cmake/api/v1/reply'
    indices = sorted(reply.glob('index-*.json'), key=lambda path: path.stat().st_mtime_ns)
    if not indices:
        raise ValueError('CMake did not produce a file API reply; rerun prepare_runtime.sh')
    index = json.loads(indices[-1].read_text())
    objects = [entry for entry in index['objects'] if entry['kind'] == 'codemodel' and entry['version']['major'] == 2]
    if len(objects) != 1:
        raise ValueError('Expected one CMake codemodel v2 reply')
    model = json.loads((reply / objects[0]['jsonFile']).read_text())
    configs = [entry for entry in model['configurations'] if entry['name'] == configuration]
    if len(configs) != 1:
        raise ValueError(f'No unique CMake configuration {configuration!r}')
    targets = {entry['name']: entry for entry in configs[0]['targets']}

    def read_target(name: str) -> dict:
        return json.loads((reply / targets[f'ann_probe_{name}']['jsonFile']).read_text())

    baseline = read_target('Baseline')
    output = ['# Resolved requirements from the pinned runtime CMake file API.\n']
    library_files = []
    for api in ('Metalium', 'STL'):
        target = read_target(api)
        group = compile_group(target)
        # Preserve the complete consumer command in its original order.
        # CMake may insert dependency-required PIC/PIE or linker flags among
        # toolchain defaults; a baseline command is not necessarily a prefix.
        # Repeating identical defaults is harmless for the same compiler and
        # build type, which the ANN configuration verifies before compiling.
        compile_options = arguments(group.get('compileCommandFragments', []))
        includes = [entry['path'] for entry in group.get('includes', [])]
        system_includes = [entry['path'] for entry in group.get('includes', []) if entry.get('isSystem')]
        definitions = [entry['define'] for entry in group.get('defines', [])]
        link = target.get('link', {})
        if link.get('lto') or link.get('sysroot') != baseline.get('link', {}).get('sysroot'):
            raise ValueError('Unsupported consumer LTO or different linker sysroot')
        fragments = link.get('commandFragments', [])
        link_options = arguments([entry for entry in fragments if entry['role'] == 'flags'])
        libraries = []
        for entry in fragments:
            if entry['role'] == 'flags':
                continue
            if entry['role'] not in ('libraries', 'libraryPath', 'frameworkPath'):
                raise ValueError(f"Unknown link command role: {entry['role']}")
            words = shlex.split(entry['fragment'])
            if words and words[0].startswith('-'):
                # CMake emits some linker flags (notably its generated rpath)
                # with role=libraries. Link-library flags are passed verbatim
                # by CMake, so retain their native shell quoting and position.
                # Decoding -Wl,-rpath,"a path" into one bare list item would
                # lose the quotes and split the path in the final link command.
                native = entry['fragment'].lstrip()
                if not native.startswith('-'):
                    raise ValueError(f'Unsupported quoted link flag: {native}')
                libraries.append(native)
                continue
            for word in words:
                # CMake link commands can use paths relative to the runtime
                # build. The ANN build lives elsewhere and needs absolute ones.
                if not word.startswith('-') and ('/' in word or word.endswith(('.a', '.so', '.dylib', '.lib'))):
                    path = Path(word)
                    path = path if path.is_absolute() else build / path
                    word = str(path.resolve())
                    if not path.is_file():
                        raise ValueError(f'Consumer library was not built: {path}')
                    library_files.append(word)
                libraries.append(word)
        name = f'TT::{api}'
        output.append(f'add_library({name} INTERFACE IMPORTED GLOBAL)\n')
        output.append(property_line(name, 'INTERFACE_INCLUDE_DIRECTORIES', includes))
        output.append(property_line(name, 'INTERFACE_SYSTEM_INCLUDE_DIRECTORIES', system_includes))
        output.append(property_line(name, 'INTERFACE_COMPILE_DEFINITIONS', definitions))
        # SHELL groups preserve flags with operands (e.g. -include header) when
        # CMake removes duplicate options in the ANN consumer.
        if compile_options:
            output.append(property_line(name, 'INTERFACE_COMPILE_OPTIONS', ['SHELL:' + shlex.join(compile_options)]))
        if link_options:
            output.append(property_line(name, 'INTERFACE_LINK_OPTIONS', ['SHELL:' + shlex.join(link_options)]))
        output.append(property_line(name, 'INTERFACE_LINK_LIBRARIES', libraries))
        output.append(property_line(name, 'INTERFACE_COMPILE_FEATURES', ['cxx_std_20']))
    # Missing dependencies should fail at configuration, even if the old
    # tt_metal shared object still exists after partial deletion of a build.
    output.append('foreach(_ann_library IN ITEMS\n')
    output.extend(f'    {literal(path)}\n' for path in dict.fromkeys(library_files))
    output.append(')\n    if(NOT EXISTS "${_ann_library}")\n'
                  '        message(FATAL_ERROR "Prepared runtime dependency missing: ${_ann_library}; rerun bash prepare_runtime.sh")\n'
                  '    endif()\nendforeach()\n')
    metadata = (output_dir / 'ann-runtime-metadata.cmake').read_text()
    config = (metadata + f'set(ANN_PREBUILT_BUILD_TYPE {literal(configuration)})\n'
              'include("${CMAKE_CURRENT_LIST_DIR}/ann-metalium-targets.cmake")\n')
    (output_dir / 'ann-metalium-targets.cmake').write_text(''.join(output))
    (output_dir / 'ann-metalium-config.cmake').write_text(config)
    library = (output_dir / f'ann-runtime-library-{configuration}.txt').read_text()
    (output_dir / 'ann-runtime-library.txt').write_text(library)
    print(f'Recorded resolved Metalium/STL consumer requirements for {configuration}')
    return list(dict.fromkeys(library_files))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('build', type=Path)
    parser.add_argument('--configuration', default='Release')
    parser.add_argument('--output', type=Path)
    args = parser.parse_args()
    try:
        snapshot(args.build, args.configuration, args.output)
    except (OSError, ValueError, KeyError) as error:
        parser.exit(1, f'ERROR: {error}\n')


if __name__ == '__main__':
    main()
