# Ask CMake to resolve the same consumer requirements as an ANN executable.
# These targets are only configuration probes; they are never built. Reading
# the file API avoids registering another export set for upstream dependencies
# (fmt/xtl already export themselves) or exporting imported system/tool targets.
if(NOT ANN_RUNTIME_EXPORT_DIR)
    set(ANN_RUNTIME_EXPORT_DIR "${CMAKE_CURRENT_BINARY_DIR}")
endif()
file(MAKE_DIRECTORY "${ANN_RUNTIME_EXPORT_DIR}")
file(WRITE "${ANN_RUNTIME_EXPORT_DIR}/ann-consumer-probe.cpp" "int main() { return 0; }\n")
foreach(_api IN ITEMS Baseline Metalium STL)
    add_executable(ann_probe_${_api} EXCLUDE_FROM_ALL "${ANN_RUNTIME_EXPORT_DIR}/ann-consumer-probe.cpp")
    set_target_properties(ann_probe_${_api} PROPERTIES CXX_STANDARD 20 CXX_STANDARD_REQUIRED YES CXX_EXTENSIONS NO)
    if(NOT _api STREQUAL "Baseline")
        target_link_libraries(ann_probe_${_api} PRIVATE TT::${_api})
    endif()
endforeach()

file(SHA256 "${ANN_PROJECT_ROOT}/tt_metal.lock.json" _lock_hash)
file(WRITE "${ANN_RUNTIME_EXPORT_DIR}/ann-runtime-metadata.cmake"
    "# Generated by prepare_runtime.sh; valid for this build and source tree.\n"
    "set(ANN_PREBUILT_RUNTIME_ROOT [==[${TT_METAL_HOME}]==])\n"
    "set(ANN_PREBUILT_LOCK_SHA256 ${_lock_hash})\n"
    "set(ANN_PREBUILT_COMPILER_ID ${CMAKE_CXX_COMPILER_ID})\n"
    "set(ANN_PREBUILT_COMPILER_VERSION ${CMAKE_CXX_COMPILER_VERSION})\n"
    "set(ANN_PREBUILT_ENABLE_LIBCXX ${ENABLE_LIBCXX})\n"
    "set(TT_ENABLE_LIGHT_METAL_TRACE ${TT_ENABLE_LIGHT_METAL_TRACE})\n")
file(GENERATE OUTPUT "${ANN_RUNTIME_EXPORT_DIR}/ann-runtime-library-$<CONFIG>.txt" CONTENT "$<TARGET_FILE:tt_metal>\n")
