if(NOT EXISTS "${_runtime_build}/ready.lock.json" OR NOT EXISTS "${_runtime_build}/ann-metalium-config.cmake")
    message(FATAL_ERROR "Prepare the pinned runtime first: bash prepare_runtime.sh")
endif()
file(SHA256 "${CMAKE_CURRENT_SOURCE_DIR}/tt_metal.lock.json" _lock_hash)
file(SHA256 "${_runtime_build}/ready.lock.json" _ready_hash)
if(NOT _lock_hash STREQUAL _ready_hash)
    message(FATAL_ERROR "The runtime lock changed; rerun bash prepare_runtime.sh")
endif()
file(READ "${_runtime_build}/ann-runtime-library.txt" _runtime_library)
string(STRIP "${_runtime_library}" _runtime_library)
if(NOT EXISTS "${_runtime_library}")
    message(FATAL_ERROR "The prepared runtime library is missing; rerun bash prepare_runtime.sh")
endif()
include("${_runtime_build}/ann-metalium-config.cmake")
if(NOT CMAKE_BUILD_TYPE STREQUAL ANN_PREBUILT_BUILD_TYPE OR CMAKE_CONFIGURATION_TYPES)
    message(FATAL_ERROR "Use the single build configuration prepared by prepare_runtime.sh (${ANN_PREBUILT_BUILD_TYPE})")
endif()
if(NOT TT_METAL_HOME STREQUAL ANN_PREBUILT_RUNTIME_ROOT OR NOT _lock_hash STREQUAL ANN_PREBUILT_LOCK_SHA256)
    message(FATAL_ERROR "The prepared runtime source moved or changed; rerun bash prepare_runtime.sh")
endif()
if(NOT CMAKE_CXX_COMPILER_ID STREQUAL ANN_PREBUILT_COMPILER_ID OR NOT CMAKE_CXX_COMPILER_VERSION VERSION_EQUAL ANN_PREBUILT_COMPILER_VERSION)
    message(FATAL_ERROR "Use the same C++ compiler as the prepared runtime")
endif()
set(ENABLE_LIBCXX "${ANN_PREBUILT_ENABLE_LIBCXX}")
